name: Test

on: [push, pull_request]

jobs:
  build_frontend:
    env:
      PLUGIN_NAME: hdr-launcher
    runs-on: ubuntu-latest
    steps:
    - name: checkout version
      uses: actions/checkout@v4.1.4

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: 20

    - run: npm install

    - run: npm run build

    - run: mkdir frontend
    - run: cp -r release frontend

    # upload built web files
    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend
        
  build_the_plugin:
    runs-on: ubuntu-24.04
    needs: build_frontend
    container: 
      image: wuboyth/skyline-plugin-builder:latest
    steps:
    - name: checkout version
      uses: actions/checkout@v4.1.4
    - uses: actions/download-artifact@v4
      name: frontend

    - run: ls -lart
    - run: "rm -rf release && cp -r frontend/* ."
    - run: "ls -lart release/*"
    - run: |
        export PATH="$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin" \
        && cd switch \
        && cargo skyline build --release --features "updater no-npm"\
        && cd ..
      env:
        HOME: /root
    - name: Upload plugin
      uses: actions/upload-artifact@v4.3.3
      with:
        name: plugin
        path: switch\target\aarch64-skyline-switch\release\libhdr_launcher_react.nro

